### ISSUE TITLE
Notification only shown once

### ISSUE THREAD

**Issue by a-dekker** [nemomobile/nemo-qml-plugin-notifications#25]
Before Sailfish 1.1.9.27/1.1.9.28 (pre SFOS 2.0), I could send notifications multiple times, but now it will only pop up the first time it is called.

No idea what is causing this change in behaviour. It is also mentioned in https://together.jolla.com/question/111708/bugnotification-only-show-once/ , but I think this is a better place to report.

**Comment by matthewvogt** [comment]
@a-dekker: Hi, thanks for the report.  

If your notification instance already has a 'replacesId' value, then re-publishing that notification should update the notification presentation with new content, without alerting the user.  I'm pretty sure I fixed some case where an updated notification was causing the preview to be incorrectly triggered, I can track it down if you need specifics.  (BTW, this behavior is defined by the Desktop Notification spec, our older behavior was faulty.)

To work around this change - instead of simply re-publishing the same notification, instead close() your notification and call publish() to create a new server-side instance.  If you have a preview configured, the publication of the new instance will trigger a new preview.

**Comment by a-dekker** [comment]
I was already experimenting with close(), but right after the publish() maybe was not the right place. Just before the publish() does work anyhow.

A site question: is there some clear documentation (ideally with examples) on such functionality? I often end up in browsing the code hoping to understand what some parameter does and if it is actually used. I especially experienced that with nemo-qml-plugin-alarm.

matthewvogt, thanks for your quick response, and I will close this issue as it is solved for me.

**Comment by matthewvogt** [comment]
No, there's really only the inline documentation which is in the comments in this file: https://github.com/nemomobile/nemo-qml-plugin-notifications/blob/master/src/notification.cpp
The resulting documentation can be installed, it's in the nemo-qml-plugin-notifications-qt5-doc package.

Partly, that's because we don't really define the behavior here, we're implementing the existing specification, which is defined here: https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html

**Comment by a-dekker** [comment]
Thanks for pointing to this, I will have a further look at it.
